services:
  tellurian:
    image: inveracity/tellurianbot:latest
    container_name: tellurianbot
    build:
      context: .
      dockerfile: docker/tellurian.Dockerfile
    command: uv run python -m tellurian
    restart: unless-stopped
    env_file:
      - .env
