version: '3.7'

services:
  tellurian:
    image: inveracity/tellurianbot:latest
    container_name: tellurianbot
    #build:
    #  context: .
    #  dockerfile: docker/tellurian.Dockerfile
    command: pipenv run bot
    restart: always
    environment:
      - TELLURIAN_DISCORD_TOKEN=${TELLURIAN_DISCORD_TOKEN}
