name: Hoplite deployment

# Only when pushing to master
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out master branch
      - uses: actions/checkout@master

      # Log in to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      # Build and publish
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/tellurian.Dockerfile
          push: true
          tags: inveracity/tellurianbot:latest

      # Deploy via Hoplite
      - name: Send a webhook to Hoplite
        uses: distributhor/workflow-webhook@v1.0.2
        env:
          webhook_auth: ${{ secrets.webhook_auth }}
          webhook_secret: ${{ secrets.webhook_secret }}
          webhook_url: ${{ secrets.webhook_url }}
          data: '{"service": "tellurianbot"}'
